#!/bin/bash
f=Seminar_presentation_CERN_25th_July_2023.tex
if pdflatex $f
then
  cd fgraph
  MPFILES=`ls *.mp`
  for MP in ${MPFILES}; do
    mpost ${MP}
  done
  cd ..
  pdflatex $f
fi
rm *.aux *.log *.nav *.out *.snm *.toc *vrb
